<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ManagercycleTeacher', 'doctrine');

/**
 * BaseManagercycleTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $managercycle_id
 * @property integer $teacher_id
 * @property integer $budget_theory
 * @property integer $budget_practice
 * @property integer $com_theory
 * @property integer $com_practice
 * @property integer $budget_telecom
 * @property integer $com_telecom
 * @property TeacherRef $TeacherRef
 * @property Managercycle $Managercycle
 * 
 * @method integer             getManagercycleId()  Returns the current record's "managercycle_id" value
 * @method integer             getTeacherId()       Returns the current record's "teacher_id" value
 * @method integer             getBudgetTheory()    Returns the current record's "budget_theory" value
 * @method integer             getBudgetPractice()  Returns the current record's "budget_practice" value
 * @method integer             getComTheory()       Returns the current record's "com_theory" value
 * @method integer             getComPractice()     Returns the current record's "com_practice" value
 * @method integer             getBudgetTelecom()   Returns the current record's "budget_telecom" value
 * @method integer             getComTelecom()      Returns the current record's "com_telecom" value
 * @method TeacherRef          getTeacherRef()      Returns the current record's "TeacherRef" value
 * @method Managercycle        getManagercycle()    Returns the current record's "Managercycle" value
 * @method ManagercycleTeacher setManagercycleId()  Sets the current record's "managercycle_id" value
 * @method ManagercycleTeacher setTeacherId()       Sets the current record's "teacher_id" value
 * @method ManagercycleTeacher setBudgetTheory()    Sets the current record's "budget_theory" value
 * @method ManagercycleTeacher setBudgetPractice()  Sets the current record's "budget_practice" value
 * @method ManagercycleTeacher setComTheory()       Sets the current record's "com_theory" value
 * @method ManagercycleTeacher setComPractice()     Sets the current record's "com_practice" value
 * @method ManagercycleTeacher setBudgetTelecom()   Sets the current record's "budget_telecom" value
 * @method ManagercycleTeacher setComTelecom()      Sets the current record's "com_telecom" value
 * @method ManagercycleTeacher setTeacherRef()      Sets the current record's "TeacherRef" value
 * @method ManagercycleTeacher setManagercycle()    Sets the current record's "Managercycle" value
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManagercycleTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('managercycle_teacher');
        $this->hasColumn('managercycle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('teacher_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('budget_theory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('budget_practice', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('com_theory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('com_practice', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('budget_telecom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('com_telecom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TeacherRef', array(
             'local' => 'teacher_id',
             'foreign' => 'id'));

        $this->hasOne('Managercycle', array(
             'local' => 'managercycle_id',
             'foreign' => 'id'));
    }
}