<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CycleSubject', 'doctrine');

/**
 * BaseCycleSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cycle_id
 * @property integer $subject_id
 * @property integer $all
 * @property integer $all_corr
 * @property integer $theory
 * @property integer $theory_corr
 * @property integer $practice
 * @property integer $practice_corr
 * @property integer $group
 * @property CycleRef $CycleRef
 * @property SubjectRef $SubjectRef
 * 
 * @method integer      getCycleId()       Returns the current record's "cycle_id" value
 * @method integer      getSubjectId()     Returns the current record's "subject_id" value
 * @method integer      getAll()           Returns the current record's "all" value
 * @method integer      getAllCorr()       Returns the current record's "all_corr" value
 * @method integer      getTheory()        Returns the current record's "theory" value
 * @method integer      getTheoryCorr()    Returns the current record's "theory_corr" value
 * @method integer      getPractice()      Returns the current record's "practice" value
 * @method integer      getPracticeCorr()  Returns the current record's "practice_corr" value
 * @method integer      getGroup()         Returns the current record's "group" value
 * @method CycleRef     getCycleRef()      Returns the current record's "CycleRef" value
 * @method SubjectRef   getSubjectRef()    Returns the current record's "SubjectRef" value
 * @method CycleSubject setCycleId()       Sets the current record's "cycle_id" value
 * @method CycleSubject setSubjectId()     Sets the current record's "subject_id" value
 * @method CycleSubject setAll()           Sets the current record's "all" value
 * @method CycleSubject setAllCorr()       Sets the current record's "all_corr" value
 * @method CycleSubject setTheory()        Sets the current record's "theory" value
 * @method CycleSubject setTheoryCorr()    Sets the current record's "theory_corr" value
 * @method CycleSubject setPractice()      Sets the current record's "practice" value
 * @method CycleSubject setPracticeCorr()  Sets the current record's "practice_corr" value
 * @method CycleSubject setGroup()         Sets the current record's "group" value
 * @method CycleSubject setCycleRef()      Sets the current record's "CycleRef" value
 * @method CycleSubject setSubjectRef()    Sets the current record's "SubjectRef" value
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCycleSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cycle_subject');
        $this->hasColumn('cycle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subject_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('all', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('all_corr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('theory_corr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('practice', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('practice_corr', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CycleRef', array(
             'local' => 'cycle_id',
             'foreign' => 'id'));

        $this->hasOne('SubjectRef', array(
             'local' => 'subject_id',
             'foreign' => 'id'));
    }
}