<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TimetableCycle', 'doctrine');

/**
 * BaseTimetableCycle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cycle_id
 * @property date $start
 * @property date $finish
 * @property Cycle $Cycle
 * 
 * @method integer        getCycleId()  Returns the current record's "cycle_id" value
 * @method date           getStart()    Returns the current record's "start" value
 * @method date           getFinish()   Returns the current record's "finish" value
 * @method Cycle          getCycle()    Returns the current record's "Cycle" value
 * @method TimetableCycle setCycleId()  Sets the current record's "cycle_id" value
 * @method TimetableCycle setStart()    Sets the current record's "start" value
 * @method TimetableCycle setFinish()   Sets the current record's "finish" value
 * @method TimetableCycle setCycle()    Sets the current record's "Cycle" value
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimetableCycle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('timetable_cycle');
        $this->hasColumn('cycle_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('start', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('finish', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cycle', array(
             'local' => 'cycle_id',
             'foreign' => 'id'));
    }
}