<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cycle', 'doctrine');

/**
 * BaseCycle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cycle_id
 * @property integer $place_id
 * @property integer $brigade
 * @property integer $manager_id
 * @property integer $brigade_est
 * @property integer $brigade_est2
 * @property integer $group_est
 * @property integer $group_est2
 * @property integer $budget_id
 * @property integer $staff_est
 * @property integer $staff_est2
 * @property integer $all_est
 * @property integer $all_est2
 * @property CycleRef $CycleRef
 * @property PlaceRef $PlaceRef
 * @property BudgetRef $BudgetRef
 * @property TeacherRef $TeacherRef
 * @property Doctrine_Collection $CycleDate
 * @property Doctrine_Collection $CycleTeacher
 * @property Doctrine_Collection $Timetable
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getCycleId()               Returns the current record's "cycle_id" value
 * @method integer             getPlaceId()               Returns the current record's "place_id" value
 * @method integer             getBrigade()               Returns the current record's "brigade" value
 * @method integer             getManagerId()             Returns the current record's "manager_id" value
 * @method integer             getBrigadeEst()            Returns the current record's "brigade_est" value
 * @method integer             getBrigadeEst2()           Returns the current record's "brigade_est2" value
 * @method integer             getGroupEst()              Returns the current record's "group_est" value
 * @method integer             getGroupEst2()             Returns the current record's "group_est2" value
 * @method integer             getBudgetId()              Returns the current record's "budget_id" value
 * @method integer             getStaffEst()              Returns the current record's "staff_est" value
 * @method integer             getStaffEst2()             Returns the current record's "staff_est2" value
 * @method integer             getAllEst()                Returns the current record's "all_est" value
 * @method integer             getAllEst2()               Returns the current record's "all_est2" value
 * @method CycleRef            getCycleRef()              Returns the current record's "CycleRef" value
 * @method PlaceRef            getPlaceRef()              Returns the current record's "PlaceRef" value
 * @method BudgetRef           getBudgetRef()             Returns the current record's "BudgetRef" value
 * @method TeacherRef          getTeacherRef()            Returns the current record's "TeacherRef" value
 * @method Doctrine_Collection getCycleDate()             Returns the current record's "CycleDate" collection
 * @method Doctrine_Collection getCycleTeacher()          Returns the current record's "CycleTeacher" collection
 * @method Doctrine_Collection getTimetableCycleSubject() Returns the current record's "TimetableCycleSubject" collection
 * @method Doctrine_Collection getTimetableCycleAction()  Returns the current record's "TimetableCycleAction" collection
 * @method Doctrine_Collection getTimetable()             Returns the current record's "Timetable" collection
 * @method Cycle               setId()                    Sets the current record's "id" value
 * @method Cycle               setCycleId()               Sets the current record's "cycle_id" value
 * @method Cycle               setPlaceId()               Sets the current record's "place_id" value
 * @method Cycle               setBrigade()               Sets the current record's "brigade" value
 * @method Cycle               setManagerId()             Sets the current record's "manager_id" value
 * @method Cycle               setBrigadeEst()            Sets the current record's "brigade_est" value
 * @method Cycle               setBrigadeEst2()           Sets the current record's "brigade_est2" value
 * @method Cycle               setGroupEst()              Sets the current record's "group_est" value
 * @method Cycle               setGroupEst2()             Sets the current record's "group_est2" value
 * @method Cycle               setBudgetId()              Sets the current record's "budget_id" value
 * @method Cycle               setStaffEst()              Sets the current record's "staff_est" value
 * @method Cycle               setStaffEst2()             Sets the current record's "staff_est2" value
 * @method Cycle               setAllEst()                Sets the current record's "all_est" value
 * @method Cycle               setAllEst2()               Sets the current record's "all_est2" value
 * @method Cycle               setCycleRef()              Sets the current record's "CycleRef" value
 * @method Cycle               setPlaceRef()              Sets the current record's "PlaceRef" value
 * @method Cycle               setBudgetRef()             Sets the current record's "BudgetRef" value
 * @method Cycle               setTeacherRef()            Sets the current record's "TeacherRef" value
 * @method Cycle               setCycleDate()             Sets the current record's "CycleDate" collection
 * @method Cycle               setCycleTeacher()          Sets the current record's "CycleTeacher" collection
 * @method Cycle               setTimetableCycleSubject() Sets the current record's "TimetableCycleSubject" collection
 * @method Cycle               setTimetableCycleAction()  Sets the current record's "TimetableCycleAction" collection
 * @method Cycle               setTimetable()             Sets the current record's "Timetable" collectionCycleSubject
 * @property Doctrine_Collection $Timetable
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getCycleId()               Returns the current record's "cycle_id" value
 * @method integer             getPlaceId()               Returns the current record's "place_id" value
 * @method integer             getBrigade()               Returns the current record's "brigade" value
 * @method integer             getManagerId()             Returns the current record's "manager_id" value
 * @method integer             getBrigadeEst()            Returns the current record's "brigade_est" value
 * @method integer             getBrigadeEst2()           Returns the current record's "brigade_est2" value
 * @method integer             getGroupEst()              Returns the current record's "group_est" value
 * @method integer             getGroupEst2()             Returns the current record's "group_est2" value
 * @method integer             getBudgetId()              Returns the current record's "budget_id" value
 * @method integer             getStaffEst()              Returns the current record's "staff_est" value
 * @method integer             getStaffEst2()             Returns the current record's "staff_est2" value
 * @method integer             getAllEst()                Returns the current record's "all_est" value
 * @method integer             getAllEst2()               Returns the current record's "all_est2" value
 * @method CycleRef            getCycleRef()              Returns the current record's "CycleRef" value
 * @method PlaceRef            getPlaceRef()              Returns the current record's "PlaceRef" value
 * @method BudgetRef           getBudgetRef()             Returns the current record's "BudgetRef" value
 * @method TeacherRef          getTeacherRef()            Returns the current record's "TeacherRef" value
 * @method Doctrine_Collection getCycleDate()             Returns the current record's "CycleDate" collection
 * @method Doctrine_Collection getCycleTeacher()          Returns the current record's "CycleTeacher" collection
 * @method Doctrine_Collection getTimetableCycleSubject() Returns the current record's "TimetableCycleSubject" collection
 * @method Doctrine_Collection getTimetableCycleAction()  Returns the current record's "TimetableCycleAction" collection
 * @method Doctrine_Collection getTimetable()             Returns the current record's "Timetable" collection
 * @method Cycle               setId()                    Sets the current record's "id" value
 * @method Cycle               setCycleId()               Sets the current record's "cycle_id" value
 * @method Cycle               setPlaceId()               Sets the current record's "place_id" value
 * @method Cycle               setBrigade()               Sets the current record's "brigade" value
 * @method Cycle               setManagerId()             Sets the current record's "manager_id" value
 * @method Cycle               setBrigadeEst()            Sets the current record's "brigade_est" value
 * @method Cycle               setBrigadeEst2()           Sets the current record's "brigade_est2" value
 * @method Cycle               setGroupEst()              Sets the current record's "group_est" value
 * @method Cycle               setGroupEst2()             Sets the current record's "group_est2" value
 * @method Cycle               setBudgetId()              Sets the current record's "budget_id" value
 * @method Cycle               setStaffEst()              Sets the current record's "staff_est" value
 * @method Cycle               setStaffEst2()             Sets the current record's "staff_est2" value
 * @method Cycle               setAllEst()                Sets the current record's "all_est" value
 * @method Cycle               setAllEst2()               Sets the current record's "all_est2" value
 * @method Cycle               setCycleRef()              Sets the current record's "CycleRef" value
 * @method Cycle               setPlaceRef()              Sets the current record's "PlaceRef" value
 * @method Cycle               setBudgetRef()             Sets the current record's "BudgetRef" value
 * @method Cycle               setTeacherRef()            Sets the current record's "TeacherRef" value
 * @method Cycle               setCycleDate()             Sets the current record's "CycleDate" collection
 * @method Cycle               setCycleTeacher()          Sets the current record's "CycleTeacher" collection
 * @method Cycle               setTimetableCycleSubject() Sets the current record's "TimetableCycleSubject" collection
 * @method Cycle               setTimetableCycleAction()  Sets the current record's "TimetableCycleAction" collection
 * @method Cycle               setTimetable()             Sets the current record's "Timetable" collectionCycleAction
 * @property Doctrine_Collection $Timetable
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getCycleId()               Returns the current record's "cycle_id" value
 * @method integer             getPlaceId()               Returns the current record's "place_id" value
 * @method integer             getBrigade()               Returns the current record's "brigade" value
 * @method integer             getManagerId()             Returns the current record's "manager_id" value
 * @method integer             getBrigadeEst()            Returns the current record's "brigade_est" value
 * @method integer             getBrigadeEst2()           Returns the current record's "brigade_est2" value
 * @method integer             getGroupEst()              Returns the current record's "group_est" value
 * @method integer             getGroupEst2()             Returns the current record's "group_est2" value
 * @method integer             getBudgetId()              Returns the current record's "budget_id" value
 * @method integer             getStaffEst()              Returns the current record's "staff_est" value
 * @method integer             getStaffEst2()             Returns the current record's "staff_est2" value
 * @method integer             getAllEst()                Returns the current record's "all_est" value
 * @method integer             getAllEst2()               Returns the current record's "all_est2" value
 * @method CycleRef            getCycleRef()              Returns the current record's "CycleRef" value
 * @method PlaceRef            getPlaceRef()              Returns the current record's "PlaceRef" value
 * @method BudgetRef           getBudgetRef()             Returns the current record's "BudgetRef" value
 * @method TeacherRef          getTeacherRef()            Returns the current record's "TeacherRef" value
 * @method Doctrine_Collection getCycleDate()             Returns the current record's "CycleDate" collection
 * @method Doctrine_Collection getCycleTeacher()          Returns the current record's "CycleTeacher" collection
 * @method Doctrine_Collection getTimetableCycleSubject() Returns the current record's "TimetableCycleSubject" collection
 * @method Doctrine_Collection getTimetableCycleAction()  Returns the current record's "TimetableCycleAction" collection
 * @method Doctrine_Collection getTimetable()             Returns the current record's "Timetable" collection
 * @method Cycle               setId()                    Sets the current record's "id" value
 * @method Cycle               setCycleId()               Sets the current record's "cycle_id" value
 * @method Cycle               setPlaceId()               Sets the current record's "place_id" value
 * @method Cycle               setBrigade()               Sets the current record's "brigade" value
 * @method Cycle               setManagerId()             Sets the current record's "manager_id" value
 * @method Cycle               setBrigadeEst()            Sets the current record's "brigade_est" value
 * @method Cycle               setBrigadeEst2()           Sets the current record's "brigade_est2" value
 * @method Cycle               setGroupEst()              Sets the current record's "group_est" value
 * @method Cycle               setGroupEst2()             Sets the current record's "group_est2" value
 * @method Cycle               setBudgetId()              Sets the current record's "budget_id" value
 * @method Cycle               setStaffEst()              Sets the current record's "staff_est" value
 * @method Cycle               setStaffEst2()             Sets the current record's "staff_est2" value
 * @method Cycle               setAllEst()                Sets the current record's "all_est" value
 * @method Cycle               setAllEst2()               Sets the current record's "all_est2" value
 * @method Cycle               setCycleRef()              Sets the current record's "CycleRef" value
 * @method Cycle               setPlaceRef()              Sets the current record's "PlaceRef" value
 * @method Cycle               setBudgetRef()             Sets the current record's "BudgetRef" value
 * @method Cycle               setTeacherRef()            Sets the current record's "TeacherRef" value
 * @method Cycle               setCycleDate()             Sets the current record's "CycleDate" collection
 * @method Cycle               setCycleTeacher()          Sets the current record's "CycleTeacher" collection
 * @method Cycle               setTimetableCycleSubject() Sets the current record's "TimetableCycleSubject" collection
 * @method Cycle               setTimetableCycleAction()  Sets the current record's "TimetableCycleAction" collection
 * @method Cycle               setTimetable()             Sets the current record's "Timetable" collection
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCycle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cycle');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cycle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('place_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('brigade', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('manager_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '7',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('brigade_est', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('brigade_est2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_est', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_est2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('budget_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('staff_est', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('staff_est2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('all_est', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('all_est2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CycleRef', array(
             'local' => 'cycle_id',
             'foreign' => 'id'));

        $this->hasOne('PlaceRef', array(
             'local' => 'place_id',
             'foreign' => 'id'));

        $this->hasOne('BudgetRef', array(
             'local' => 'budget_id',
             'foreign' => 'id'));

        $this->hasOne('TeacherRef', array(
             'local' => 'manager_id',
             'foreign' => 'id'));

        $this->hasMany('CycleDate', array(
             'local' => 'id',
             'foreign' => 'cycle_id'));

        $this->hasMany('CycleTeacher', array(
             'local' => 'id',
             'foreign' => 'cycle_id'));

        $this->hasMany('TimetableCycleSubject', array(
             'local' => 'id',
             'foreign' => 'cycle_id'));

        $this->hasMany('TimetableCycleAction', array(
             'local' => 'id',
             'foreign' => 'cycle_id'));

        $this->hasMany('Timetable', array(
             'local' => 'id',
             'foreign' => 'cycle_id'));
    }
}