<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PlanRef', 'doctrine');

/**
 * BasePlanRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Managercycle
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getManagercycle() Returns the current record's "Managercycle" collection
 * @method PlanRef             setId()           Sets the current record's "id" value
 * @method PlanRef             setName()         Sets the current record's "name" value
 * @method PlanRef             setManagercycle() Sets the current record's "Managercycle" collection
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plan_ref');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Managercycle', array(
             'local' => 'id',
             'foreign' => 'plan_id'));
    }
}