<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CycleDate', 'doctrine');

/**
 * BaseCycleDate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cycle_id
 * @property date $start
 * @property date $finish
 * @property Cycle $Cycle
 * 
 * @method integer   getCycleId()  Returns the current record's "cycle_id" value
 * @method date      getStart()    Returns the current record's "start" value
 * @method date      getFinish()   Returns the current record's "finish" value
 * @method Cycle     getCycle()    Returns the current record's "Cycle" value
 * @method CycleDate setCycleId()  Sets the current record's "cycle_id" value
 * @method CycleDate setStart()    Sets the current record's "start" value
 * @method CycleDate setFinish()   Sets the current record's "finish" value
 * @method CycleDate setCycle()    Sets the current record's "Cycle" value
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCycleDate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cycle_date');
        $this->hasColumn('cycle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('finish', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cycle', array(
             'local' => 'cycle_id',
             'foreign' => 'id'));
    }
}