<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubjectRef', 'doctrine');

/**
 * BaseSubjectRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $CycleSubject
 * @property Doctrine_Collection $CycleTeacher
 * @property Doctrine_Collection $TimetableCycleSubject
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method Doctrine_Collection getCycleSubject()          Returns the current record's "CycleSubject" collection
 * @method Doctrine_Collection getCycleTeacher()          Returns the current record's "CycleTeacher" collection
 * @method Doctrine_Collection getTimetableCycleSubject() Returns the current record's "TimetableCycleSubject" collection
 * @method SubjectRef          setId()                    Sets the current record's "id" value
 * @method SubjectRef          setName()                  Sets the current record's "name" value
 * @method SubjectRef          setCycleSubject()          Sets the current record's "CycleSubject" collection
 * @method SubjectRef          setCycleTeacher()          Sets the current record's "CycleTeacher" collection
 * @method SubjectRef          setTimetableCycleSubject() Sets the current record's "TimetableCycleSubject" collection
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubjectRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject_ref');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CycleSubject', array(
             'local' => 'id',
             'foreign' => 'subject_id'));

        $this->hasMany('CycleTeacher', array(
             'local' => 'id',
             'foreign' => 'subject_id'));

        $this->hasMany('TimetableCycleSubject', array(
             'local' => 'id',
             'foreign' => 'subject_id'));
    }
}