<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TimetableAction', 'doctrine');

/**
 * BaseTimetableAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $contraction
 * @property Doctrine_Collection $TimetableCycleAction
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getContraction()          Returns the current record's "contraction" value
 * @method Doctrine_Collection getTimetableCycleAction() Returns the current record's "TimetableCycleAction" collection
 * @method TimetableAction     setName()                 Sets the current record's "name" value
 * @method TimetableAction     setContraction()          Sets the current record's "contraction" value
 * @method TimetableAction     setTimetableCycleAction() Sets the current record's "TimetableCycleAction" collection
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimetableAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('timetable_action');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contraction', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TimetableCycleAction', array(
             'local' => 'id',
             'foreign' => 'action_id'));
    }
}