<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AgreementRef', 'doctrine');

/**
 * BaseAgreementRef
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $short_name
 * @property Doctrine_Collection $TeacherRef
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getShortName()  Returns the current record's "short_name" value
 * @method Doctrine_Collection getTeacherRef() Returns the current record's "TeacherRef" collection
 * @method AgreementRef        setId()         Sets the current record's "id" value
 * @method AgreementRef        setName()       Sets the current record's "name" value
 * @method AgreementRef        setShortName()  Sets the current record's "short_name" value
 * @method AgreementRef        setTeacherRef() Sets the current record's "TeacherRef" collection
 * 
 * @package    timetable
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAgreementRef extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('agreement_ref');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('short_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TeacherRef', array(
             'local' => 'id',
             'foreign' => 'agreement_id'));
    }
}