<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/12/11 12:50:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=centre',
  'username' => 'root',
  'password' => 123,
  'name' => 'doctrine',
)),);
