<?php

/**
 * AgreementRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgreementRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AgreementRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AgreementRef');
    }
}