<?php

/**
 * BudgetRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetRef');
    }
}