<?php

/**
 * CycleDateTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CycleDateTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object CycleDateTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('CycleDate');
	}
	
	public function getSelect($iCycleId) {
		return $this->createQuery('d')
				->select("CONCAT(DATE_FORMAT(d.start, '%d.%m.%Y'), ' - ', DATE_FORMAT(d.finish, '%d.%m.%Y')) AS cycle_date,"
						. "d.start AS start, d.finish AS finish")
				->where('d.cycle_id = ?', $iCycleId)
				->orderBy('d.start')
				->fetchArray();
	}

}
