<?php

/**
 * CycleTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CycleTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object CycleTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('Cycle');
	}
	
	public function getSelect() {
		return $this->createQuery('c')
				->select("c.id AS id, CONCAT(cr.name, ' (', ir.name, ', ', course.name, ')') AS cycle_name")
				->leftJoin('c.CycleRef cr')
				->leftJoin('cr.InstructionRef ir')
				->leftJoin('cr.CourseRef course')
				->orderBy('cycle_name')
				->fetchArray();
	}
	
	public function getNameWithInstructionAndCourse($iCycleId) {
		return $this->createQuery('c')
				->select("CONCAT(cr.name, ' (', ir.name, ', ', course.name, ')') AS cycle_name")
				->leftJoin('c.CycleRef cr')
				->leftJoin('cr.InstructionRef ir')
				->leftJoin('cr.CourseRef course')
				->where('c.id = ?', $iCycleId)
				->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
	}

}
