<?php

/**
 * CycleTeacherTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CycleTeacherTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object CycleTeacherTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('CycleTeacher');
	}

	public function getSubjects($iCycleId) {
		return $this->createQuery('ct')
						->select('ct.cycle_id, sr.name AS subject_name, tr.name AS teacher_name')
						->leftJoin('ct.SubjectRef sr')
						->leftJoin('ct.TeacherRef tr')
						->where('ct.cycle_id = ?', $iCycleId)
						->orderBy('subject_name')
						->fetchArray();
	}

}
