<?php

/**
 * CycleRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CycleRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CycleRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CycleRef');
    }
}