<?php

/**
 * CycleSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CycleSubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CycleSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CycleSubject');
    }
}