<?php

/**
 * InstructionRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstructionRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstructionRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstructionRef');
    }
}