<?php

/**
 * ManagercycleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManagercycleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManagercycleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Managercycle');
    }
}