<?php

/**
 * ManagercycleTeacherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManagercycleTeacherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManagercycleTeacherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManagercycleTeacher');
    }
}