<?php

/**
 * PlaceRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaceRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaceRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlaceRef');
    }
}