<?php

/**
 * PlanRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanRef');
    }
}