<?php

/**
 * StaffRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaffRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaffRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaffRef');
    }
}