<?php

/**
 * SubjectRefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubjectRefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubjectRefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubjectRef');
    }
}