<?php

/**
 * TimetableTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimetableTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object TimetableTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('Timetable');
	}

	public function getTimetableId($iCycleId, $sStart, $sFinish, $iBrigadeCount, $sTown, $iHourCount) {
		$oQuery = $this->createQuery('t')
				->select('t.id')
				->where('t.cycle_id = ?', $iCycleId)
				->andWhere('t.start = ?', $sStart)
				->andWhere('t.finish = ?', $sFinish);
		if (isset($sTown) && $sTown) {
			$oQuery->andWhere('t.town = ?', $sTown);
		}
		$oBrigadeQuery = clone $oQuery;
		$oBrigadeQuery->andWhere('t.brigade_count = ?', $iBrigadeCount);

		$iTimetableId = $oBrigadeQuery->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
		if (!$iTimetableId) {
			$iTimetableId = $oQuery->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
			if (!$iTimetableId) {
				$oTimetable = new Timetable();
				$oTimetable->cycle_id = $iCycleId;
				$oTimetable->start = $sStart;
				$oTimetable->finish = $sFinish;
				$oTimetable->brigade_count = $iBrigadeCount;
				$oTimetable->hour_count = $iHourCount;
				if (isset($sTown) && $sTown) {
					$oTimetable->town = $sTown;
				}
				$oTimetable->save();
				$iTimetableId = $oTimetable->getId();
			} else {
				$oTimetable = TimetableTable::getInstance()
						->findOneBy('id', $iTimetableId);
				$oTimetable->brigade_count = $iBrigadeCount;
				$oTimetable->hour_count = $iHourCount;
				$oTimetable->save();
			}
		}
		return $iTimetableId;
	}

}
