<?php

/**
 * TimetableActionItemTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimetableActionItemTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object TimetableActionItemTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('TimetableActionItem');
	}

	public function getEntityIdsUnique($iTimetableId) {
		$aEntityIds = $this->createQuery('i')
				->select('i.entity_id AS entity_id')
				->where('i.timetable_id = ?', $iTimetableId)
				->fetchArray();
		$aEntityIdsUnique = array();
		foreach ($aEntityIds as $aEntityId) {
			$aEntityIdsUnique[] = $aEntityId['entity_id'];
		}
		return array_unique($aEntityIdsUnique, SORT_NUMERIC);
	}

	public function getTelecommCount($iTimetableId) {
		return $this->createQuery('i')
						->select('COUNT(i.id)')
						->where('i.timetable_id = ?', $iTimetableId)
						->andWhere('i.is_telecommunication = 1')
						->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
	}

}
