<?php

/**
 * TimetableActionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TimetableActionTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object TimetableActionTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('TimetableAction');
	}

}
