<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('timetable_cycle', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'cycle_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'start' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             'finish' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('timetable_cycle_subject', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'timetable_cycle_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'subject_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'teacher_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'subject_contraction' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'teacher_contraction' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('timetable_cycle');
        $this->dropTable('timetable_cycle_subject');
    }
}