<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_cycle', 'timetable_cycle_cycle_id_cycle_id', array(
             'name' => 'timetable_cycle_cycle_id_cycle_id',
             'local' => 'cycle_id',
             'foreign' => 'id',
             'foreignTable' => 'cycle',
             ));
        $this->createForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_timetable_cycle_id_timetable_cycle_id', array(
             'name' => 'timetable_cycle_subject_timetable_cycle_id_timetable_cycle_id',
             'local' => 'timetable_cycle_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_cycle',
             ));
        $this->createForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_subject_id_subject_ref_id', array(
             'name' => 'timetable_cycle_subject_subject_id_subject_ref_id',
             'local' => 'subject_id',
             'foreign' => 'id',
             'foreignTable' => 'subject_ref',
             ));
        $this->createForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_teacher_id_teacher_ref_id', array(
             'name' => 'timetable_cycle_subject_teacher_id_teacher_ref_id',
             'local' => 'teacher_id',
             'foreign' => 'id',
             'foreignTable' => 'teacher_ref',
             ));
        $this->addIndex('timetable_cycle', 'timetable_cycle_cycle_id', array(
             'fields' => 
             array(
              0 => 'cycle_id',
             ),
             ));
        $this->addIndex('timetable_cycle_subject', 'timetable_cycle_subject_timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_id',
             ),
             ));
        $this->addIndex('timetable_cycle_subject', 'timetable_cycle_subject_subject_id', array(
             'fields' => 
             array(
              0 => 'subject_id',
             ),
             ));
        $this->addIndex('timetable_cycle_subject', 'timetable_cycle_subject_teacher_id', array(
             'fields' => 
             array(
              0 => 'teacher_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_cycle', 'timetable_cycle_cycle_id_cycle_id');
        $this->dropForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_timetable_cycle_id_timetable_cycle_id');
        $this->dropForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_subject_id_subject_ref_id');
        $this->dropForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_teacher_id_teacher_ref_id');
        $this->removeIndex('timetable_cycle', 'timetable_cycle_cycle_id', array(
             'fields' => 
             array(
              0 => 'cycle_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_subject', 'timetable_cycle_subject_timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_subject', 'timetable_cycle_subject_subject_id', array(
             'fields' => 
             array(
              0 => 'subject_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_subject', 'timetable_cycle_subject_teacher_id', array(
             'fields' => 
             array(
              0 => 'teacher_id',
             ),
             ));
    }
}