<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('timetable_cycle_action', 'cycle_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('timetable_cycle_subject', 'cycle_id', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('timetable_cycle_action', 'cycle_id');
        $this->removeColumn('timetable_cycle_subject', 'cycle_id');
    }
}