<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_cycle_action', 'timetable_cycle_action_timetable_cycle_id_timetable_cycle_id', array(
             'name' => 'timetable_cycle_action_timetable_cycle_id_timetable_cycle_id',
             'local' => 'timetable_cycle_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_cycle',
             ));
        $this->createForeignKey('timetable_cycle_action', 'timetable_cycle_action_teacher_id_teacher_ref_id', array(
             'name' => 'timetable_cycle_action_teacher_id_teacher_ref_id',
             'local' => 'teacher_id',
             'foreign' => 'id',
             'foreignTable' => 'teacher_ref',
             ));
        $this->createForeignKey('timetable_cycle_action', 'timetable_cycle_action_action_id_timetable_action_id', array(
             'name' => 'timetable_cycle_action_action_id_timetable_action_id',
             'local' => 'action_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_action',
             ));

        $this->addIndex('timetable_cycle_action', 'timetable_cycle_action_timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_id',
             ),
             ));
        $this->addIndex('timetable_cycle_action', 'timetable_cycle_action_teacher_id', array(
             'fields' => 
             array(
              0 => 'teacher_id',
             ),
             ));
        $this->addIndex('timetable_cycle_action', 'timetable_cycle_action_action_id', array(
             'fields' => 
             array(
              0 => 'action_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_cycle_action', 'timetable_cycle_action_timetable_cycle_id_timetable_cycle_id');
        $this->dropForeignKey('timetable_cycle_action', 'timetable_cycle_action_teacher_id_teacher_ref_id');
        $this->dropForeignKey('timetable_cycle_action', 'timetable_cycle_action_action_id_timetable_action_id');
        $this->removeIndex('timetable_cycle_action', 'timetable_cycle_action_timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_action', 'timetable_cycle_action_teacher_id', array(
             'fields' => 
             array(
              0 => 'teacher_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_action', 'timetable_cycle_action_action_id', array(
             'fields' => 
             array(
              0 => 'action_id',
             ),
             ));
    }
}