<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable', 'timetable_cycle_id_cycle_id', array(
             'name' => 'timetable_cycle_id_cycle_id',
             'local' => 'cycle_id',
             'foreign' => 'id',
             'foreignTable' => 'cycle',
             ));
        $this->createForeignKey('timetable_item', 'timetable_item_timetable_id_timetable_id', array(
             'name' => 'timetable_item_timetable_id_timetable_id',
             'local' => 'timetable_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable',
             ));
        $this->createForeignKey('timetable_item', 'ttti', array(
             'name' => 'ttti',
             'local' => 'timetable_cycle_subject_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_cycle_subject',
             ));
        $this->addIndex('timetable', 'timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'cycle_id',
             ),
             ));
        $this->addIndex('timetable_item', 'timetable_item_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->addIndex('timetable_item', 'timetable_item_timetable_cycle_subject_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_subject_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable', 'timetable_cycle_id_cycle_id');
        $this->dropForeignKey('timetable_item', 'timetable_item_timetable_id_timetable_id');
        $this->dropForeignKey('timetable_item', 'ttti');
        $this->removeIndex('timetable', 'timetable_cycle_id', array(
             'fields' => 
             array(
              0 => 'cycle_id',
             ),
             ));
        $this->removeIndex('timetable_item', 'timetable_item_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->removeIndex('timetable_item', 'timetable_item_timetable_cycle_subject_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_subject_id',
             ),
             ));
    }
}