<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_action_item', 'timetable_action_item_timetable_id_timetable_id', array(
             'name' => 'timetable_action_item_timetable_id_timetable_id',
             'local' => 'timetable_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable',
             ));
        $this->createForeignKey('timetable_action_item', 'tttai', array(
             'name' => 'tttai',
             'local' => 'timetable_cycle_action_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_cycle_action',
             ));
        $this->addIndex('timetable_action_item', 'timetable_action_item_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->addIndex('timetable_action_item', 'timetable_action_item_timetable_cycle_action_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_action_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_action_item', 'timetable_action_item_timetable_id_timetable_id');
        $this->dropForeignKey('timetable_action_item', 'tttai');
         $this->removeIndex('timetable_action_item', 'timetable_action_item_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->removeIndex('timetable_action_item', 'timetable_action_item_timetable_cycle_action_id', array(
             'fields' => 
             array(
              0 => 'timetable_cycle_action_id',
             ),
             ));
    }
}