<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_item', 'timetable_item_entity_id_timetable_cycle_subject_id', array(
             'name' => 'timetable_item_entity_id_timetable_cycle_subject_id',
             'local' => 'entity_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable_cycle_subject',
             ));
        $this->addIndex('timetable_item', 'timetable_item_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_item', 'timetable_item_entity_id_timetable_cycle_subject_id');
        $this->removeIndex('timetable_item', 'timetable_item_entity_id', array(
             'fields' => 
             array(
              0 => 'entity_id',
             ),
             ));
    }
}