<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('timetable_action_item', 'timetable_cycle_action_id');
        $this->addColumn('timetable_action_item', 'entity_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('timetable_action_item', 'timetable_cycle_action_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('timetable_action_item', 'entity_id');
    }
}