<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('timetable_action_item', 'is_telecommunication', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('timetable_item', 'is_telecommunication', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('timetable_action_item', 'is_telecommunication');
        $this->removeColumn('timetable_item', 'is_telecommunication');
    }
}