<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('timetable_cycle_action', 'timetable_cycle_action_timetable_id_timetable_id', array(
             'name' => 'timetable_cycle_action_timetable_id_timetable_id',
             'local' => 'timetable_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable',
             ));
        $this->createForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_timetable_id_timetable_id', array(
             'name' => 'timetable_cycle_subject_timetable_id_timetable_id',
             'local' => 'timetable_id',
             'foreign' => 'id',
             'foreignTable' => 'timetable',
             ));
        $this->addIndex('timetable_cycle_action', 'timetable_cycle_action_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->addIndex('timetable_cycle_subject', 'timetable_cycle_subject_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('timetable_cycle_action', 'timetable_cycle_action_timetable_id_timetable_id');
        $this->dropForeignKey('timetable_cycle_subject', 'timetable_cycle_subject_timetable_id_timetable_id');
        $this->removeIndex('timetable_cycle_action', 'timetable_cycle_action_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
        $this->removeIndex('timetable_cycle_subject', 'timetable_cycle_subject_timetable_id', array(
             'fields' => 
             array(
              0 => 'timetable_id',
             ),
             ));
    }
}