<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('timetable_cycle_action', 'timetable_id', 'integer', '8', array(
             ));
        $this->addColumn('timetable_cycle_subject', 'timetable_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('timetable_cycle_action', 'timetable_id');
        $this->removeColumn('timetable_cycle_subject', 'timetable_id');
    }
}