<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/17 16:11:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=centre',
  'username' => 'root',
  'password' => 123,
  'name' => 'doctrine',
)),);
